name: Run ML Training

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Mengunduh kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Langkah 2: Menyiapkan Conda Environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          python-version: '3.13' # Sesuaikan dengan versi python di conda.yaml Anda

      # Langkah 3: Menginstall MLflow (Instal di environment base Conda)
      - name: Install MLflow
        shell: bash -l {0} # Gunakan shell yang diinisialisasi Conda
        run: pip install mlflow

      # Langkah 4: Menjalankan proses training menggunakan MLflow
      - name: Run MLflow Project
        shell: bash -l {0} # Gunakan shell yang diinisialisasi Conda
        # Pindah ke folder MLProject dulu
        working-directory: ./MLProject 
        # Jalankan mlflow dari dalam folder MLProject
        run: mlflow run .
